### ISSUE TITLE
AttributeError exception within an exception block

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSMonitoring#28]
When trying to use CMSMonitoring 0.2.1 from the WMCore services, with this patch applied:
https://github.com/dmwm/WMCore/pull/9214

I get the following exception:
```
2019-07-03 14:20:10,346:ERROR:HeartbeatMonitorBase:Failed to send data to StompAMQ. Error 'StompAMQ' object has no attribute '_ip_and_ports'
Traceback (most recent call last):
  File "/data/srv/HG1907f-comp2/sw.amaltaro/slc7_amd64_gcc630/cms/workqueue/1.2.4/lib/python2.7/site-packages/WMCore/REST/HeartbeatMonitorBase.py", line 80, in uploadToAMQ
    failures = stompSvc.send(notifications)
  File "/data/srv/HG1907f-comp2/sw.amaltaro/slc7_amd64_gcc630/external/cmsmonitoring/0.2.1/lib/python2.7/site-packages/CMSMonitoring/StompAMQ.py", line 263, in send
    conn = self.connect() # provide random connection to brokers
  File "/data/srv/HG1907f-comp2/sw.amaltaro/slc7_amd64_gcc630/external/cmsmonitoring/0.2.1/lib/python2.7/site-packages/CMSMonitoring/StompAMQ.py", line 228, in connect
    msg += 'Available hosts: %s' % self._ip_and_ports
AttributeError: 'StompAMQ' object has no attribute '_ip_and_ports'
2019-07-03 14:20:10,423:INFO:HeartbeatMonitorBase:Uploaded to WMStats...
```

The attribute name is `ip_and_ports`, not `_ip_and_ports`.

BTW, since the error happened while handling a connection exception, it also suggests there was a problem connecting to the AMQ system. Has this version been properly tested using user credentials (instead of grid certificate)?

**Comment by vkuznet** [comment]
Alan, yes I discovered this too, just a week ago and the fix was applied in this commit commit f8f557e5b9f8e961c1fe6a593ca4114e6a210b9c

But I haven't time yet to build release and upload it. The AMQ error happen because (most likely) the node you're using is not ipv6 aware (this is where in my case error happened).

**Comment by vkuznet** [comment]
Here is new PR for CMSMonitoring package (version 0.2.2): https://github.com/cms-sw/cmsdist/pull/5070

**Comment by amaltaro** [comment]
Then please document and make it clear that there is a requirement that ipv6 must be load and enabled in the OS.

About this bug, you could have mentioned it when I tagged you in yesterday's PR.

**Comment by vkuznet** [comment]
Alan,
I'm not sure that we should impose ipv6 requirement yet since CERN brokers have
both ipv4 and ipv6 nodes. And, I need some input from CERN IT on that topic.

Regarding comment on a tag, I simply overlook, dealing with 100+ emails every
morning is quite tedious.

**Comment by amaltaro** [comment]
BTW, I think your fix won't work. I applied it locally and here you go:
```
...
  File "/data/srv/HG1907f-comp2/sw.amaltaro/slc7_amd64_gcc630/external/cmsmonitoring/0.2.1/lib/python2.7/site-packages/CMSMonitoring/StompAMQ.py", line 228, in connect
    msg += 'Available hosts: %s' % self.ip_and_ports
TypeError: can only concatenate tuple (not "str") to tuple
```

In addition to that, please get back on that WMCore PR once you have more information and further instructions to integrate CMSMonitoring into other projects.

**Comment by vkuznet** [comment]
Alan, there were few fixes last week and new release addressed this, e.g. the final version of code has this:
https://github.com/dmwm/CMSMonitoring/blob/master/src/python/CMSMonitoring/StompAMQ.py#L229

So, you need new release.
